version: '3'
services:
  test:
    build:
      context: .
      dockerfile: test/Dockerfile
    network_mode: service:test-redis
  test-redis:
    image: redis

  storagenode:
    image: storjlabs/storagenode:${VERSION}
    environment:
    - SATELLITE_ADDR=satellite:7777
    links:
    - satellite
  satellite:
    image: storjlabs/satellite:${VERSION}
    environment:
    - API_KEY=abc123
    - BOOTSTRAP_ADDR=localhost:8080
    - IDENTITY_ADDR=:7777
    - MOCK_OVERLAY_NODES=INTENTIONALLY:LEFT:BLANK
    links:
    - redis
    depends_on:
    - redis
  redis:
    image: redis
  uplink:
    image: storjlabs/uplink:${VERSION}
    command: --min-threshold 1 --max-threshold 1 --repair-threshold 1 --success-threshold 1
    environment:
    - API_KEY=abc123
    - SATELLITE_ADDR=satellite:7777
    ports:
    - 7777:7777
